Switch back to GHCR (#14)
* Switch back to GHCR

* Output the digest of the pushed docker image

* Try out on a feature branch

* Fix the workflow syntax

* Try a different approach

* Fix a typo

* Change the way we extract the digest

* Hä?

* Does this fix the issue? I need to finally work on a local testing env

* Remote the extra -t

* Now it should finally work!

* Use another method to parse the digest

* What about this?

* Fix the syntax error

* Don't run on feature branches

diff --git a/scripts/ci/docker_build_and_push b/scripts/ci/docker_build_and_push
--- a/scripts/ci/docker_build_and_push
+++ b/scripts/ci/docker_build_and_push
@@ -15,19 +15,24 @@
 
 set -e
 
+log() {
+  printf "%s\n" "$@" >&2
+}
+
 # Validate required environment variables
 if [[ -z "$CONTAINER_REGISTRY" || -z "$IMAGE_NAME" || -z "$CI_ENV" ]]; then
-  echo "Error: Missing required environment variables."
-  echo "Please set CONTAINER_REGISTRY, IMAGE_NAME, and CI_ENV."
-  echo "CONTAINER_REGISTRY is the URL of the container registry (e.g. ghcr.io)."
-  echo "IMAGE_NAME is the name of the Docker image (e.g. myorg/myapp)."
-  echo "Possible values for CI_ENV: gha, gitlab-ci, local."
+  log "Error: Missing required environment variables."  \
+      "Please set CONTAINER_REGISTRY, IMAGE_NAME, and CI_ENV." \
+      "CONTAINER_REGISTRY is the URL of the container registry (e.g. ghcr.io)." \
+      "IMAGE_NAME is the name of the Docker image (e.g. myorg/myapp)." \
+      "Possible values for CI_ENV: gha, gitlab-ci, local."
   exit 1
 fi
 
 if [ "$#" -ne 2 ]; then
-    echo "Usage: $0 <version> <commit_sha>"
-    echo "Example: $0 v1.2.3 a1b2c3d4e5f6"
+    log "Usage: $0 <version> <commit_sha>" \
+        "Example: $0 v1.2.3 a1b2c3d4e5f6"
+
     exit 1
 fi
 
@@ -45,26 +50,40 @@ cache_from_type="local"
 cache_to_type="local,mode=max"
 
 if [[ "$CI_ENV" == "gha" ]]; then
-    echo "Running on GitHub Actions..."
-    echo "Configured Docker to use the GHA cache."
+    log "Running on GitHub Actions..." \
+        "Configured Docker to use the GHA cache."
+
     cache_from_type="gha"
     cache_to_type="gha,mode=max"
 elif [[ "$CI_ENV" == "gitlab-ci" ]]; then
-  echo "Running on GitLab CI..."
-  echo "Configured Docker to use the GitLab CI cache."
+  log "Running on GitLab CI..." \
+      "Configured Docker to use the GitLab CI cache."
+
   cache_from_type="registry"
   cache_to_type="registry,mode=max"
 fi
 
+# Image tags with -t flags hardcoded
+tags=(
+  "$CONTAINER_REGISTRY/$IMAGE_NAME:$version"
+  "$CONTAINER_REGISTRY/$IMAGE_NAME:$commit_sha"
+  "$CONTAINER_REGISTRY/$IMAGE_NAME:latest"
+)
+
 docker build \
   --cache-from type="$cache_from_type" \
   --cache-to type="$cache_to_type" \
-  -t "$CONTAINER_REGISTRY"/"$IMAGE_NAME":"$version" \
-  -t "$CONTAINER_REGISTRY"/"$IMAGE_NAME":"$commit_sha" \
-  -t "$CONTAINER_REGISTRY"/"$IMAGE_NAME":latest \
+  -t "${tags[0]}" \
+  -t "${tags[1]}" \
+  -t "${tags[2]}" \
   .
-docker push "$CONTAINER_REGISTRY"/"$IMAGE_NAME":"$version"
-docker push "$CONTAINER_REGISTRY"/"$IMAGE_NAME":"$commit_sha"
-docker push "$CONTAINER_REGISTRY"/"$IMAGE_NAME":latest
+
+# Push all tags
+for tag in "${tags[@]}"; do
+  PUSH_OUTPUT=$(docker push "$tag")
+done
+
+# Extract the digest from the last push output
+echo "$PUSH_OUTPUT" | grep "digest: sha256:" | awk '{print $3}'
 
 set +x
